### ISSUE TITLE
Feature to disable avro namespaces

### ISSUE THREAD

**Issue by MarcoLugo** [Ten0/serde_avro_fast#21]
Thank you for this crate, it's definitely an improvement over `apache_avro` :)

One minor issue (more of an inconvenience) that we found when migrating from `apache_avro` is that `serde_avro_fast`'s derive macro includes `namespace` by default into the schemas. This caused some issues that we managed to solve by using annotations to set namespaces to empty strings (i.e. `#[avro_schema(namespace = "")]`).

I wonder if something like a `disable_namespaces` feature could be implemented so that it could be completely turned off in `Cargo.toml` if desired. This would also ensure backwards compatibility for current users while improving dev experience.

**Comment by Ten0** [comment]
Hello, tanks for opening this issue.

Unless I'm mistaken, if we didn't include a namespace that depends on the module name in the schema, there would be no good way to represent the following:
```rust
mod mod_1 {
    #[derive(BuildSchema, Serialize)]
    struct StructA {
        foo: i32,
    }
}
mod mod_2 {
    #[derive(BuildSchema, Serialize)]
    struct StructA {
        bar: i32,
    }
}

#[derive(BuildSchema, Serialize)]
struct StructB {
    a: mod_1::StructA,
    b: mod_2::StructA,
}
```

It's not allowed by avro to have two structs in the same namespace (here, `null` namespace as per avro terminology, if we don't specify any namespace) that have the same name but aren't the same struct.
Because of this, and because the actual namespaces and struct names in the schema don't matter as much as the fact the schema has to be valid (they are only used for factoring struct definitions), I've chosen to have the default behavior of setting a namespace that guarantees distinction between structs based on the crate and module they live in, so that it just works out of the box no matter the module tree.
When overriding namespaces, it becomes your responsibility to ensure that there are no name collisions.

The issue with being able to disable this via a feature flag would be that this wouldn't be an additive feature, while features in Rust are supposed to be additive: due to the way the feature resolver works in Rust, if this was a feature flag, adding to your dependencies any crate that enables this feature would make every other crate that uses `serde_avro_fast` anywhere in the dependency tree have this feature enabled too, and suddenly ignore namespaces, potentially breaking it (because of the issue highlighted above).
Consequently, I think this would be better represented as a function call on a given schema than a feature flag.

Which brings me to my next point: I think what you're trying to achieve (IIUC, getting rid of namespaces in your final schema without specifying `namespace=""` on every struct) can already be achieved programatically without features, by patching the generated schema before it's turned into an immutable schema, using first [`BuildSchema::schema_mut()`](https://docs.rs/serde_avro_derive/0.2.3/serde_avro_derive/trait.BuildSchema.html#method.schema_mut) then patching the namespace of each node using [`SchemaMut::nodes_mut()`](https://docs.rs/serde_avro_fast/1.1.2/serde_avro_fast/schema/struct.SchemaMut.html#method.nodes_mut) before finally turning it into a regular fully-computed schema with [`SchemaMut::freeze`](https://docs.rs/serde_avro_fast/1.1.2/serde_avro_fast/schema/struct.SchemaMut.html#method.freeze).
```rust
let mut schema: SchemaMut = StructB::schema_mut(); // This is also on the BuildSchema trait (in fact, `BuildSchema::schema()` is just `BuildSchema::schema_mut().freeze()`)
for node in schema.nodes_mut() {
    // Post-patch the nodes to e.g. remove namespaces on Record, Fixed and Enum
    match node {
        ...
    }
}
let schema: Schema = schema.freeze();
```

Using this model it should be possible to define a `clear_namespaces()` function that you may then use like so:

```rust
lazy_static! {
    // It's always best to only compute the schema once, not at every serialization, so a lazy_static is a good place to have it
    // It's also probably best to have a #[test] that an instance of the struct successfully serializes with this schema
    // so that it's guaranteed that it successfully initializes following the namespace patch (and is consistent with the struct)
    static ref SCHEMA: Schema = clear_namespaces(StructB::schema_mut()).freeze().unwrap();
}
```

Please let me know whether that is an appropriate solution for your use-case. 🙂

**Comment by MarcoLugo** [comment]
That's exactly it and the suggested solution is perfect, thank you!
