### ISSUE TITLE
derive for `Schema`

### ISSUE THREAD

**Issue by droundy** [Ten0/serde_avro_fast#3]
I'd love to see a derive macro for the `Schema`, as my single larges pain point with `apache-avro` is the lack of a well-implemented derive macro.  Specifically, I'd like to have a schema generator that is guaranteed to match what serde does, with a way to create "leaf" types manually.

I understand I could use the `apache-avro` derive macro and then translate the schema, but of course then I'd be stuck with the same bad derive macro.

**Comment by Ten0** [comment]
Hi! 
That's an interesting issue. 🙂
It something I haven't needed myself because the schemas were pre-defined in my use-case.

It seems that such a thing exists as https://github.com/apache/avro/tree/main/lang/rust/avro_derive.
Note that the schema produced by that crate can be converted into a `serde_avro_fast::Schema` via [`Schema::from_apache_schema`](https://docs.rs/serde_avro_fast/0.3.2/serde_avro_fast/schema/struct.Schema.html#method.from_apache_schema). 
What are the specific limitations you encounter there?

**Comment by Ten0** [comment]
Closing because there seems to already be a crate that does this and author hasn't expressed how it doesn't fit their need.

**Comment by Ten0** [comment]
Because 1.0 unties from `apache-avro` and consequently doesn't interact as well with `avro_derive`, I've published [`serde_avro_derive`](docs.rs/serde_avro_derive/) as a replacement to build a `serde_avro_fast` schema directly from a derive on the source struct.
