### ISSUE TITLE
Object container file encoding serialization support

### ISSUE THREAD

**Issue by droundy** [Ten0/serde_avro_fast#4]
The documentation I can find involves `(raw data, no headers…)`, but it would be nice to have clear a top-level example showing how to create a proper avro file (or Vec that could be written to a file) and how to read one (including confirmation that the header matches the schema).

**Comment by Ten0** [comment]
IIUC you're talking about [object container file encoding](https://avro.apache.org/docs/current/specification/#object-container-files). 

If that's indeed the case, it is documented here : https://docs.rs/serde_avro_fast/0.3.2/serde_avro_fast/object_container_file_encoding/index.html

However I haven't implemented the serialization to object container files yet (only got deserialization atm), notably because it involved a few opinionated choices with regards to blocks sizes.

I should probably have a look at the sizes chosen by other implementations and make it possible for the user to choose it. 

Another related potential improvement would be to update the reader so that if blocks are not(/never) too large, it doesn't use stream decompression but instead decompresses block by block. (This is a compromise between how much time it takes to to obtain the first record of the block, and how much time total it takes to process the file.)

Is that indeed object container file encoding that you're talking about?  (If yes I may implement it soon.)

**Comment by Ten0** [comment]
So I've been working on this and I'll be releasing a new version with writer support soon. (And a fix in the reader which would only read the first block.)

**Comment by Ten0** [comment]
I have published object container file Writer support in v0.4.0. 🚀

Documentation is [here for `Writer`](https://docs.rs/serde_avro_fast/latest/serde_avro_fast/object_container_file_encoding/struct.Writer.html) and [here for `write_all`](https://docs.rs/serde_avro_fast/latest/serde_avro_fast/object_container_file_encoding/fn.write_all.html).

Please let me know if anything is unclear 😊
